### ISSUE TITLE
Please update npm package

### ISSUE THREAD

**Issue by urlund** [digitickets/star-web-print#3]
Hi,

First of all, thanks for this package.

With that said, i spend quite a while debugging why I couldn't get it to work, until I discovered that the 1.6.0 release available as npm install is not the same as the current master version (which works).

So again, please update your npm package :)

**Comment by rquadling** [comment]
Hello and thank you for your comment.

@antriver Should we add a `-1` patch level to the version so it is not the same as what we have previously released?

`1.6.0` is Star's version and then `-1` is our patch level, making `1.6.0-1`?

**Comment by rquadling** [comment]
I've just looked at Star's site and see that there are some potential changes coming in June 2020 that may affect this library's usage and may already be affecting it for some environments.

But with that, @antriver , should we release this as `1.6.0-1` as the first DT patch to v1.6.0 from Star?

**Comment by rquadling** [comment]
@antriver Probably also worth adding some notes to the README.md about the expected usage/integration as it is different to Star's way.

**Comment by urlund** [comment]
Any news on this? :)

**Comment by rquadling** [comment]
@urlund 

We have published 1.6.1. Please take a look at README.md to see the changes we have made and how we are going to resolve the versioning in the future.

If you have any issues, please come back to us. We will be glad to help.

**Comment by urlund** [comment]
@rquadling Awesome, thanks!

**Comment by rquadling** [comment]
@urlund Just FYI, both v1.7.0+1 and v1.8.0+1 have just been released. We'll try to keep uptodate with Star's releases more often!

**Comment by rquadling** [comment]
@urlund 5 years on and I eventually get to v1.9.0. But it looks like Star's last release was 7th July 2023, so as uptodate as it can be.
